use core::time;
use std::collections::HashSet;
use std::thread;

use rspotify::clients::BaseClient;
use rspotify::prelude::Id;
use rspotify::{
    ClientCredsSpotify,
    model::{AlbumId, Image},
};
use serde_json::json;
use sqlx::PgPool;
use tracing::info;
use url::Url;

use crate::{
    MARKET,
    entries::{self, EntryCreateModel, EntryType},
    with_height,
};

pub async fn import_all(db: &PgPool, spotify: &ClientCredsSpotify) -> anyhow::Result<()> {
    let entries: Vec<(i16, &str)> = vec![
        (
            3,
            "https://open.spotify.com/album/7FzyHVSmmcg1EZjMKzHYPc?si=YBRy13u_SNeBnWgeBSdWDg",
        ),
        (
            4,
            "https://open.spotify.com/album/5cqmUy0SSI9L0DrMoyo2ks?si=q1q_JviBQ3yU-05jHjilvg",
        ),
        (
            5,
            "https://open.spotify.com/album/36r6Pu9fvulQIcPw5UCDW6?si=G9F_I3JOR76-YkKIISYRPw",
        ),
        (
            1,
            "https://open.spotify.com/album/6tiNM64RHJum8Z9k4DCfv7?si=o45_flYKQrqpLSN8-jKx1w",
        ),
        (
            2,
            "https://open.spotify.com/album/38yV9x3cozEvpatqWlCjFj?si=NoU16jP_SRyPBsGkBscVyQ",
        ),
        (
            5,
            "https://open.spotify.com/album/6DN8vyJ89VvIuaJrQNoxol?si=baIbsct5SMKfnRqrAlD4tw",
        ),
        (
            12,
            "https://open.spotify.com/album/1pV9ZitMywO46h4igOPD2X?si=zjMPGR8ZQy2d3oesCsTR0A",
        ),
        (
            2,
            "https://open.spotify.com/album/1PJEIVW1Kr3qN75jUNd8Wb?si=iFKN_H-eQcqTulT8KAiJ1g",
        ),
        (
            6,
            "https://open.spotify.com/album/26xSieq1whEkCKaSfZgwwr?si=WTSveYmKRx6hCM9KriHvYA",
        ),
        (
            5,
            "https://open.spotify.com/album/12ZryW5TiyMAq0S4xYSmn3?si=ypmSM3KtTuOJb0K8XMYi4w",
        ),
        (
            3,
            "https://open.spotify.com/album/5lveWt8ckwlwrnShHurIbH?si=qiRTmd_BRvWwnyYtzAJFjA",
        ),
        (
            1,
            "https://open.spotify.com/album/5mK72HovxbiKVcgtOBNwik?si=UwYnqkEPRSSeA8h5yFFxjg",
        ),
        (
            6,
            "https://open.spotify.com/album/7g9oI6MyAwMOheznKQc7GX?si=R_a8Zcm9QliD7DxndZxajg",
        ),
        (
            2,
            "https://open.spotify.com/album/2nhD3yVzpPlkQZCKsM2jI9?si=8wJSBvBkSOGLSJWltVKI4A",
        ),
        (
            2,
            "https://open.spotify.com/album/3XOw4trhdnP6D6qIfWzy0b?si=aNQ_c6C1STebKDpSLZY71A",
        ),
        (
            6,
            "https://open.spotify.com/album/2Xhhdx6lKpwEPa07oXPOZa?si=CH7Pb87EQ2iMkKL-VfXz9Q",
        ),
        (
            2,
            "https://open.spotify.com/album/0aoF0ZLxsdO3PGoTqAtldz?si=H5JLN6v7SD6OTYpAMs29tw",
        ),
        (
            11,
            "https://open.spotify.com/album/0Zlzie7V9eAE3veEIqjUUf?si=STnoRuvUTUCcVaDD6N8stg",
        ),
        (
            5,
            "https://open.spotify.com/album/5YbNfHrlC8pNScfGBOBcs5?si=LNl-ejfKRpqJkkCAHmp-ew",
        ),
        (
            3,
            "https://open.spotify.com/album/6bCDp732XNWBKCTQA5l15r?si=jpCbrktgRxW8_G7JYk6SBw",
        ),
        (
            4,
            "https://open.spotify.com/album/4VjgjeIgk71Rt8WHIShMvK?si=Fq1y218pRXm6QKAYC2OdzQ",
        ),
        (
            1,
            "https://open.spotify.com/album/2DuTGuZAnJtxBwYKI9DJ7H?si=-zaEiv4yQ_K3mAKBEjCxtg",
        ),
        (
            0,
            "https://open.spotify.com/album/3ANkD069p7sujMWGFYL7Gk?si=YHrXffvJQDKbReWu0qjgqg",
        ),
        (
            1,
            "https://open.spotify.com/album/5pDlWwNtOK3CheIcs1stBR?si=kM7iKlV7T4WXwz2mlNYTIg",
        ),
        (
            5,
            "https://open.spotify.com/album/7qeMWKOavSYt562C3GVgSK?si=I3nR4BjnSCiOIB1MUPITDQ",
        ),
        (
            4,
            "https://open.spotify.com/album/1WMlZtBPnIt04GqfHpzd6k?si=8bd22V_8RYO7xRT7-y8m9Q",
        ),
        (
            2,
            "https://open.spotify.com/album/2Q5SvJxKhmg3PupIQ6iZrx?si=xi9WHx17Qt626LMPrhfDqQ",
        ),
        (
            6,
            "https://open.spotify.com/album/3LKt3pUAhnVxbbax4nV12l?si=laNHR6wJSuqwpKMoLK0ixw",
        ),
        (
            6,
            "https://open.spotify.com/album/06QeFJJCebVi4Ha4IRe1QK?si=WA6pHxFwSvqtWRRHExqrOQ",
        ),
        (
            2,
            "https://open.spotify.com/album/1beUHMcmHaBDPS3wdHl4jY?si=NBgQzzTnQ9u0FmJ7ncwdQA",
        ),
        (
            8,
            "https://open.spotify.com/album/2psWDBpuMuQF9yIcXiqN4F?si=QwSAhqtjQE2_LI3T4wL7ew",
        ),
        (
            5,
            "https://open.spotify.com/album/5sSJsOzD8bpeoY1URIIRM0?si=kUubUjs-R2u8a2uO8t-1yQ",
        ),
        (
            7,
            "https://open.spotify.com/album/0ff010CHo9upK9GAVa77YF?si=bw9e2cxfQZmvE_s6-EY1Tw",
        ),
        (
            23,
            "https://open.spotify.com/album/2xto6MS3O5kFfJ9ro7CEhG?si=EOE0I0VkRnWnmsQ3gjFPRQ",
        ),
        (
            3,
            "https://open.spotify.com/album/40pHFqjf9m00ckHNLHpeeS?si=hq_X2x2MSyaBIkW-7BxkhA",
        ),
        (
            8,
            "https://open.spotify.com/album/1JjkQ53xpIzLDRyeL7Yo5D?si=bWdt8GZ9RQefyPpoWVnLFw",
        ),
        (
            4,
            "https://open.spotify.com/album/6sUBnKxutUBRKsIK74VNi6?si=O-dK4fmMTXyT4TC6AztPMQ",
        ),
        (
            15,
            "https://open.spotify.com/album/1wqVcEMkS80HriPRDMgcIi?si=lg8GUHKDRX2qUT48CneAaA",
        ),
        (
            7,
            "https://open.spotify.com/album/76RNK8qPfpJoPpW1W5qvtp?si=feTvBwFcQBO3H75Fl9BfRg",
        ),
        (
            5,
            "https://open.spotify.com/album/2MiRyV93MmCSqgGNV6ULyL?si=V9cKsN10T5yHs2L279ZBsw",
        ),
        (
            6,
            "https://open.spotify.com/album/22SNdtsRPtmVeUj1eLaMfl?si=FHhR8LwLTECYtyZgRRr-kA",
        ),
        (
            2,
            "https://open.spotify.com/album/4KeOh5uVjGcNx0nDKQTY4f?si=KmejuYEjRsO4gCz8TDjZWg",
        ),
        (
            5,
            "https://open.spotify.com/album/5ghsOkrgV3X91sFPXatcGt?si=ZMdV5PL6RCa6WgTUOTlVTQ",
        ),
        (
            20,
            "https://open.spotify.com/album/432whneUEeGiBAUJCDiiwR?si=CmfB29EcQ-uV-E8E_eeJBA",
        ),
        (
            4,
            "https://open.spotify.com/album/7MIAyjYS7cSp6FpcqjR4AX?si=S19yReuWRoe80fnllZZUsQ",
        ),
        (
            2,
            "https://open.spotify.com/album/5jTAIeE1zoZOagT0ERsUjX?si=PnbFR2TzQ6OLhjHcvYWFng",
        ),
        (
            4,
            "https://open.spotify.com/album/20qWR1yU6GGKFvNB9QZUZk?si=UqzHLS2eRTmVO-vlz35tNw",
        ),
        (
            4,
            "https://open.spotify.com/album/6QgztThO9jCZAJkw4JkCbB?si=oAxfy0PMRDG4UHda3DISeg",
        ),
        (
            3,
            "https://open.spotify.com/album/0gBq2rX4kFaflYPEaFd5qC?si=c1eUXUY6RuyZU5QcYYdiSg",
        ),
        (
            8,
            "https://open.spotify.com/album/3VxXxgKlzJYoxKQHmikX6w?si=tBG5fVM6QmCodmPYrhR6fA",
        ),
        (
            2,
            "https://open.spotify.com/album/3GDCT2cAeYOQByty9GQHHQ?si=KfXscME6Qo-zLUSJqYebeQ",
        ),
        (
            2,
            "https://open.spotify.com/album/5MR55umz0Hk0Gz2iSemVy8?si=5RTqmmkIRsChI1Tz9TRR8g",
        ),
        (
            5,
            "https://open.spotify.com/album/5Lgonbj5oL1uhPBnOmsd36?si=poVOcRxXQ4u8bu4hhgsuMw",
        ),
        (
            1,
            "https://open.spotify.com/album/3RQQUQqqlWObaTqwcfkA7t?si=DBeYcUPrSreH5S9zQnhlAg",
        ),
        (
            1,
            "https://open.spotify.com/album/39Xi8HCPOjj7pn8y76CNwM?si=_xTLhf_GQYW_D6D1UBJabw",
        ),
        (
            6,
            "https://open.spotify.com/album/1YfMrQjspDYj3akVCM8QnA?si=R-vmMcYXRuGmNniLo5YPVw",
        ),
        (
            14,
            "https://open.spotify.com/album/1RyZWk4rDNqmvz6nmOQgmP?si=2cYuk3ZYR_G3L-YWo5KU5g",
        ),
        (
            4,
            "https://open.spotify.com/album/77fSpZwF12HYJRt58UKFIb?si=nTEyJPCSS4Ws2aH8JPSc-w",
        ),
        (
            1,
            "https://open.spotify.com/album/7LCuF1AGy5pwiBS7Chqg4B?si=pp-S13dDTQqKsYarpizdYA",
        ),
        (
            1,
            "https://open.spotify.com/album/2DomjnBGoT5guh9WM0PdGW?si=8gkJzxYGQGSurWPpYmelFg",
        ),
        (
            6,
            "https://open.spotify.com/album/6gZranOqwMmS9ORc65ejIQ?si=LFtmt7E9RiSX_WYb2j6E6g",
        ),
        (
            4,
            "https://open.spotify.com/album/1TL383C1cIJAodhPAd7BNE?si=ZAeY-xD6SKaTQzOG358XtA",
        ),
        (
            3,
            "https://open.spotify.com/album/2NHyCmlzFBxKJJNsvu7BH1?si=FdEs0L2mTAag4wx-A4c6vA",
        ),
        (
            4,
            "https://open.spotify.com/album/43qvuKBw1mi6nLmmWMBcuY?si=kCWYYCfaRrmDiBCzuFZd5g",
        ),
        (
            6,
            "https://open.spotify.com/album/2R1liNlbMwNYy4iuUOxLdw?si=mfIbfSXlRzypjeIOr8cfxg",
        ),
        (
            3,
            "https://open.spotify.com/album/0TAwnHe59S1WvIaGSXVq75?si=4J5TKQtuSGe74aFb_VucXw",
        ),
        (
            1,
            "https://open.spotify.com/album/2rU2I21uuhtKimlRPZTveX?si=gUiaWrxGTKq8b7pLlju93Q",
        ),
        (
            1,
            "https://open.spotify.com/album/3V5Ij1wqvzqHC6ZoDCKU6h?si=xwQSSKUmRzKMXZ_QEbN9bA",
        ),
        (
            2,
            "https://open.spotify.com/album/1ut0uHARGd6rd2u1sTkKuY?si=sn76lZ5HQZKGzW1ig_HKRA",
        ),
        (
            10,
            "https://open.spotify.com/album/2XG2Yc35xnduSiBllza82G?si=ZKXZg3nBSgOqOHqJsq8xVA",
        ),
        (
            2,
            "https://open.spotify.com/album/2WViA4GvDY25YYrQYb9PsR?si=yIh3dz14SjunJgKem9GYDA",
        ),
        (
            1,
            "https://open.spotify.com/album/2ycRWGy7XTuhIzWP5MZOqi?si=TvCJCofARm-mAXpc04_hbA",
        ),
        (
            5,
            "https://open.spotify.com/album/5mQg8r5ivI0IX5bTV57KyN?si=SPp_liiRQlSLWASuVdsCUQ",
        ),
        (
            8,
            "https://open.spotify.com/album/50d2KMK7GtbCTfLqxDfHIS?si=jDHKz-Q3QwaORvOcbdLUxQ",
        ),
        (
            1,
            "https://open.spotify.com/album/105UQAEjLpiqUCUK6x6i3g?si=UibCAV8uQRCgmvOkXLcKmQ",
        ),
        (
            4,
            "https://open.spotify.com/album/5qvokPibHLO3e47oV4wyhz?si=uPy_RwLqRuawhnV4PMISVQ",
        ),
        (
            0,
            "https://open.spotify.com/album/0zDRwoqvJYhvfhcvQYzfcZ?si=ssTy9vrTQwW268vNWsinhg",
        ),
        (
            3,
            "https://open.spotify.com/album/7KEMmRYdYTyOkHaoocjwp7?si=P-yVrchETK6FULQEgD-sBw",
        ),
        (
            0,
            "https://open.spotify.com/album/4M3VGzWy7xxm93zGw0xqAU?si=f-hcVbU8R1a0v8lkNlfGAw",
        ),
        (
            1,
            "https://open.spotify.com/album/5ZcAMixtzUYEBZNVSrixNE?si=CMiLOh_jRZ-qKYcPNm1hxw",
        ),
        (
            3,
            "https://open.spotify.com/album/4SVQrvQkXzYC1nU7DfDJx2?si=zltTrpjXQuagXhlaekGEbw",
        ),
        (
            1,
            "https://open.spotify.com/album/2FRfGv6pQommVYHmqJKqU5?si=0M64Zcs3SE2LE5vQxzGOfQ",
        ),
        (
            5,
            "https://open.spotify.com/album/3CVr8yD3EmmbTAD3mgdkst?si=MjeqO79mTPm6g1-Z4oljgA",
        ),
        (
            0,
            "https://open.spotify.com/album/3M7f1Ta7DdY49Cj0bsHchW?si=Y-RVTRaKTHCFHeWWX4j69w",
        ),
        (
            1,
            "https://open.spotify.com/album/7HIZJWnLo11Fsv68HPhjgj?si=lw04w8VXQoSVOnXTqjV1Wg",
        ),
        (
            0,
            "https://open.spotify.com/album/6FLO3ExDCl0GwkzjCQGq0x?si=nFMppWOFQzuCrlyf04GNPw",
        ),
        (
            1,
            "https://open.spotify.com/album/4I3xNROKxdLC2GFcpp8o2R?si=74MMVxpKTYWA-N9843YgCA",
        ),
        (
            0,
            "https://open.spotify.com/album/3xIGmydqrJOShru5bQmSVa?si=PWZnyEHTQbmSOjjKN079cw",
        ),
        (
            3,
            "https://open.spotify.com/album/4MvsJSPLzWm6irgVI2PXfo?si=GN0xXAViToy18_y0EQSI-A",
        ),
        (
            8,
            "https://open.spotify.com/album/0pIth1U2QD7sdvjt4xpRvS?si=VHUNBpvoT2yo6BxxrDFdng",
        ),
        (
            3,
            "https://open.spotify.com/album/4IMxyQClyxn6nLxYAK1BDs?si=SaDUTvbXSFK2IJMn4UZX5g",
        ),
        (
            0,
            "https://open.spotify.com/album/0qybrewjst6zJBOrdBghc2?si=Dyeq67Z_QtWMo_LJ40PZaQ",
        ),
        (
            8,
            "https://open.spotify.com/album/7DA8OgWsVgCSM5ayHEOQHo?si=-ICkG8XGRg6uPyCivCRZ-g",
        ),
        (
            6,
            "https://open.spotify.com/album/1q9psu1dvUemN0x8tFnwhr?si=AaSJOICRTvehDea9PQmtCQ",
        ),
        (
            6,
            "https://open.spotify.com/album/43vchxiKkr9Ybb3KpBi7Lv?si=liaDwTZrQBiQ9KID5oWevg",
        ),
        (
            1,
            "https://open.spotify.com/album/3DSLB9jRkpszgyfVJvxJmT?si=PFH1JuoVSyiFQbvhKx32Eg",
        ),
        (
            3,
            "https://open.spotify.com/album/77982WeUjCZe5dVMbcLQK6?si=MRaMZdw9RRiGjYXX_7mLrg",
        ),
        (
            3,
            "https://open.spotify.com/album/1FBxm3v11F66t91vtfbyrc?si=VdToSxDaR_Kcgwa6QYqXSQ",
        ),
        (
            11,
            "https://open.spotify.com/album/28FrVzhi3fzo7z7jxAo3Ca?si=bH6yNwRMSRaNScC9wyQIDA",
        ),
        (
            9,
            "https://open.spotify.com/album/61wKiQ2c9m3NDSvbFAxQow?si=CjcWsjpJSgWoo7f7IIJyFA",
        ),
        (
            2,
            "https://open.spotify.com/album/6bDEtcCNZmHK6oPWSYmVjW?si=DPYoTppHSgSjV9WAD5wMvA",
        ),
        (
            8,
            "https://open.spotify.com/album/58TLbfTManCWgskqrKrwnF?si=ANaPfY8pS0i5k3MBPB36xA",
        ),
        (
            3,
            "https://open.spotify.com/album/0jet89yX7ilugi5WNk3bG7?si=kBDR9Gq9TeqBYbNNdcfopw",
        ),
        (
            2,
            "https://open.spotify.com/album/03C4G0dGKUXaPRCw1iGIP9?si=bhYfT72aQViEUu4w_mXrqw",
        ),
        (
            8,
            "https://open.spotify.com/album/0sBR6VO3ZRvqvrxhBPDECl?si=_yOCgZ2VS5OhQO11X0zbCQ",
        ),
        (
            7,
            "https://open.spotify.com/album/5cbOhNmUxxf2quWl9LlZCC?si=TLshxULlRmic9JNVqJZZLA",
        ),
        (
            23,
            "https://open.spotify.com/album/7xjYJmNYtMxGrdh6zZLmzO?si=p9rstJUmRxyMw-HUQ42BGg",
        ),
        (
            1,
            "https://open.spotify.com/album/48ggaHb1KvtbMcGWdgTB3o?si=peeQRHtqR96TJVCbb3Y6Pg",
        ),
        (
            2,
            "https://open.spotify.com/album/0twfexlftR2UDXnMV7D0WT?si=h5TSp1oQRSW_aLdAhekkSA",
        ),
        (
            3,
            "https://open.spotify.com/album/6howISKaY5WaA4OhsAf7wC?si=ljJIZrO0Q_qrG4tDBdAkEg",
        ),
        (
            2,
            "https://open.spotify.com/album/6juJdEr5nwDQsB7Tf4QHgp?si=6tpiFUPwSbuAkZhBPo1Gdg",
        ),
        (
            3,
            "https://open.spotify.com/album/1BUhqipQSsUrlT4oYMCNfu?si=ErLGeJhGQZGcKSJ5ZTumzw",
        ),
        (
            4,
            "https://open.spotify.com/album/4HNyJ5I1rliINqGdh4e1Sj?si=lIR5mP42QM2dkZxzk5GVYg",
        ),
        (
            0,
            "https://open.spotify.com/album/3bV1m0EaVEuypHDFBRKJZV?si=aG8NCz57TSKs37BEBceTyQ",
        ),
        (
            0,
            "https://open.spotify.com/album/2lNa4HNsJKKLo4akamU2NS?si=xjBausYsQU6eN-2hOOvHQQ",
        ),
        (
            3,
            "https://open.spotify.com/album/0G3Qu6fawshPa7eM585RjS?si=oUDF_DisSammnNH2gxs-7Q",
        ),
        (
            1,
            "https://open.spotify.com/album/3O5eIrkFUKsxiTDIRXnbVq?si=VZ_tBl1aSZiQzbd28gSXNQ",
        ),
        (
            2,
            "https://open.spotify.com/album/3rkbAMJ9FZr3nzFseI5ILP?si=rdJq1-vDSVae4pbs0sJZaQ",
        ),
        (
            5,
            "https://open.spotify.com/album/36AbK7MtDuPAplH24PgQjT?si=qXup2-yMR_KGH3kt55ig0A",
        ),
        (
            8,
            "https://open.spotify.com/album/4p2X0WTZ1F0jNJ7rh0A1hF?si=3ArWVl5yQJGASX2kdGRKUg",
        ),
        (
            2,
            "https://open.spotify.com/album/77TbMwFcu8lBAnorSn6pip?si=MMxNVKWTQSGFM7rlmBHWDw",
        ),
        (
            3,
            "https://open.spotify.com/album/2DhkzrgWzGb0I7XPgs4uqA?si=3Xw1BHhGRKG04sEDl1lXog",
        ),
        (
            2,
            "https://open.spotify.com/album/36as0OY246iZyT4hzCsYvl?si=RvRPoa-_STOV3U_d7FX9vw",
        ),
        (
            3,
            "https://open.spotify.com/album/0UdbLbzP72CouY45FhiJan?si=N-0br6s2SVWTreBoa6uLwg",
        ),
        (
            2,
            "https://open.spotify.com/album/3LyfzXhN5ExLhPqaasYd7Z?si=YeGRNvhMTD-WNy06VEUxIw",
        ),
        (
            2,
            "https://open.spotify.com/album/2XPa5ccswP7n9JFgzW4r1l?si=aRQv1TqQTOCqW0huBWfzUw",
        ),
        (
            4,
            "https://open.spotify.com/album/1Sd7bF2ZKQW6H0yJRRLxnk?si=lPqr2rKHSye-ObE76A0TNg",
        ),
        (
            3,
            "https://open.spotify.com/album/3D59wmJHjlL8ggyC2KVLBi?si=1jmLrXBXQSWQT9a2lW4P2Q",
        ),
        (
            5,
            "https://open.spotify.com/album/78x2X30ZogObYin6H88nD8?si=RdAocrPDSuyGzMZiyHSyAQ",
        ),
        (
            3,
            "https://open.spotify.com/album/058DSqZkbS2BcleJ4woQKx?si=rdySt_WTR8exHCBcrOifcg",
        ),
        (
            2,
            "https://open.spotify.com/album/4FIbJGEqIqDAyiBxgo5d0g?si=xPkciBZQTwO5S_UCe7UCKg",
        ),
        (
            5,
            "https://open.spotify.com/album/149NjUKxSClxxtiDdgZjG6?si=TMPfM8gxRlGZ9k1RM2xpoA",
        ),
        (
            3,
            "https://open.spotify.com/album/0EZzdiBCBVYxZQ6uK8XePc?si=-lk3h5G9TsyfSLWaB_czBA",
        ),
        (
            6,
            "https://open.spotify.com/album/67Iagy03Kvp79xhNGviK5V?si=cWHnfza_S5inI6fClK4pIg",
        ),
        (
            3,
            "https://open.spotify.com/album/49YfNjC0JgrZ5M88OELdtC?si=YJYrd1EMTfy0r4u5XxXzXw",
        ),
        (
            3,
            "https://open.spotify.com/album/7jnkIzom7WQ7pRgW9qc6Fd?si=WEo8m-b9TtOi4BYL-r1GMg",
        ),
        (
            2,
            "https://open.spotify.com/album/24buaw3qXTDggAgJYUnf0c?si=scK0MGM9ThOT57Y3GPeA_g",
        ),
        (
            6,
            "https://open.spotify.com/album/6JhgZ0EwcAQDhGwzGDfo9s?si=AsoAD5saRseFeLSPN4-49g",
        ),
        (
            3,
            "https://open.spotify.com/album/0fwNMMRv7xTgQ2fEAyssd7?si=K_Gj-ZjmRSmnYFipC2_h5w",
        ),
        (
            3,
            "https://open.spotify.com/album/29ekZAt57t6aVimWrEUPuo?si=zNgPTRYRQgiF3wlSFpi7Cw",
        ),
        (
            11,
            "https://open.spotify.com/album/1qljDQPe4qzLHUDeSsPTat?si=wVwGvMxdQCGziCzivj2DIg",
        ),
        (
            1,
            "https://open.spotify.com/album/6ptptx47oj8BQZNp4cYziC?si=Z5RVCdQURMm7W463-BTgzA",
        ),
        (
            11,
            "https://open.spotify.com/album/1gJZRSfvXDCnHhYnl5DgWd?si=nVuVORm2TierDDW4gHm7Vg",
        ),
        (
            1,
            "https://open.spotify.com/album/4i88Sl4GloZyRjcDsmqey0?si=kDL_HxScTiStp97X-5n8-g",
        ),
        (
            3,
            "https://open.spotify.com/album/3gq1hlZOc6uEau6tZASsLk?si=8K3ep0ZuRkS6YQfsIiShhg",
        ),
        (
            2,
            "https://open.spotify.com/album/0SGWfaeT5YUqymn7qz5XD7?si=DoYdmduZTheohf6DB1pzLw",
        ),
        (
            1,
            "https://open.spotify.com/album/7EharB8Nk0HcLAfygiM1sE?si=aOwPLCwsRgOh1MyyXpn-Ag",
        ),
        (
            3,
            "https://open.spotify.com/album/030RTn30Qx2Zdp8lXuWLul?si=_NsoMgqcTnmF7f14FM0j6g",
        ),
        (
            2,
            "https://open.spotify.com/album/1QBzhyvurkePsaSNOmsrmT?si=Z63v89uISmqi6tQ74nKgSQ",
        ),
        (
            3,
            "https://open.spotify.com/album/6LJz7VdDRBJYCxdutpEt8r?si=Qzc675cQReynUtPtnHn3Uw",
        ),
        (
            2,
            "https://open.spotify.com/album/0XupZYOqS98FMMpohIvOMS?si=Z4Vuz0zoRNKrxFYBHKiZag",
        ),
        (
            6,
            "https://open.spotify.com/album/1ABWznZoIswD59bCp9cyFO?si=r5YWQstwQfuf189OWNsCqw",
        ),
        (
            10,
            "https://open.spotify.com/album/02xEJkxzCzEADbnKacOhLJ?si=prvsHEZvQA6RpSBXLCJuFg",
        ),
        (
            27,
            "https://open.spotify.com/album/3bbFly6zBqFp6Sp5jk2n1V?si=O2lVOjvmRVOe624SyJzNIA",
        ),
        (
            1,
            "https://open.spotify.com/album/4D3freTvvr9R3IY9ffoPJE?si=LXsjrMNJRQS5rWMg8x7FCQ",
        ),
        (
            15,
            "https://open.spotify.com/album/3MpO7ItzjK8ADRMq3q9nmt?si=-vjLE1Q0Qr6i8557p_u5Lg",
        ),
        (
            3,
            "https://open.spotify.com/album/2LaaedYUhpMjgkjU9b4EGi?si=AsOTnNH0Qg2OcdKlaoxfVQ",
        ),
        (
            1,
            "https://open.spotify.com/album/1HKQ4d298PtVxT0a4BQsng?si=YtHW6VrlR3i25KyPf4KUyg",
        ),
        (
            12,
            "https://open.spotify.com/album/0WKXcZesO4alcDdC8JKIKF?si=xxu6x3JZSzK0x2MgD9xupw",
        ),
        (
            1,
            "https://open.spotify.com/album/36CwCR1wz682jxOLSUaUwh?si=gO5KbqzHT6SqyOUAXB8wqg",
        ),
        (
            3,
            "https://open.spotify.com/album/2OB0I2qW3RwixCtNEPE09h?si=2PnrTVHORQigZdTYbIuP9w",
        ),
        (
            3,
            "https://open.spotify.com/album/60r4JW9AcLzEPrQIRoJ31p?si=zatGyDQ5QoGP6I-DmR8i_g",
        ),
        (
            1,
            "https://open.spotify.com/album/4OQG4LrKxdnLTVySPDJHMu?si=y7lgGVOFSKmUiWXbuFMR_w",
        ),
        (
            4,
            "https://open.spotify.com/album/4VK7kXVsdXgjMScbJ0N5nQ?si=1eqE06GDRv-aYYDbyhrJdw",
        ),
        (
            4,
            "https://open.spotify.com/album/38spOYbeJNMMrsTjYB9zvZ?si=epZWtodKSpW_cXVUxCL6jA",
        ),
        (
            2,
            "https://open.spotify.com/album/3fyNFOUjASIxPs7UZ9KUFa?si=2d2cmZ3kSkCiwlOQBDQQiA",
        ),
        (
            6,
            "https://open.spotify.com/album/1WiMMZmOiXbElhKsABYhoe?si=-DO_mefXSzCGNW2BnsBKHw",
        ),
        (
            2,
            "https://open.spotify.com/album/2QqNmRzGhBuZEvnVtZ395D?si=LKZIMcruQoWhz3iU_m52Dg",
        ),
        (
            1,
            "https://open.spotify.com/album/18PmfTT50ZhdRU5eTioC9u?si=-8R9UAfMTaOyQe4_vIhKag",
        ),
        (
            3,
            "https://open.spotify.com/album/4e52BWpvxiKJkchO5ZQ93T?si=KKtvq_e_QOy8FJbb2EscKQ",
        ),
        (
            1,
            "https://open.spotify.com/album/11DG5mOSJ3NemVQZ9ILk56?si=zF6iytmHQbijxaBt-YvBCQ",
        ),
        (
            11,
            "https://open.spotify.com/album/10jDUzZRwXSjTSb1EuHXtp?si=1WJd8HzcQTeVen93x1xOIg",
        ),
        (
            8,
            "https://open.spotify.com/album/5JsPKtQJU88xZwD9Yp14Cj?si=GZhoEPBOSHubdyCGTJTSqQ",
        ),
        (
            6,
            "https://open.spotify.com/album/4mighm3zEOKeMp4MfIjE6a?si=NU0YJPWhQKKZN0bLKWvImw",
        ),
        (
            1,
            "https://open.spotify.com/album/2hieie9qV5PHeDNKLNz3E5?si=r2DQvSwVTeGA6eS4nzoOlw",
        ),
        (
            4,
            "https://open.spotify.com/album/4i9tIqsLzBBJU51lKZU9EH?si=ZoCRk125QFWzJEhud9yLUQ",
        ),
        (
            12,
            "https://open.spotify.com/album/5fbokeTcDgn4PR0WSIKwgF?si=GIO4jBDvT16RqpuOFhTuRA",
        ),
        (
            5,
            "https://open.spotify.com/album/3ktNgL0KljiK2z33ts22ER?si=PSwTLSdAQBOYx-4f1eWSNA",
        ),
        (
            11,
            "https://open.spotify.com/album/09au3ViAkjIjJA4dEjIJTp?si=T2xkvRCRQQWO7Mz59E1qxA",
        ),
        (
            6,
            "https://open.spotify.com/album/1OxYQUMBCLapsrsnrH3Cov?si=qbCljgNtRYKzpJcFqVfGog",
        ),
        (
            5,
            "https://open.spotify.com/album/1tW4dRjZcw9s5QO3pvRBmn?si=LtJLnek_ShuHKtjU5t0wkA",
        ),
        (
            2,
            "https://open.spotify.com/album/25Lgg3wsQK2vEdZ8ZHzBpk?si=E3W4uqX0SuCGcH09revS8g",
        ),
        (
            1,
            "https://open.spotify.com/album/3lgKAQ5pKOML2JcRN614nS?si=QVKkOdYiSpqSonSD6IA61Q",
        ),
        (
            7,
            "https://open.spotify.com/album/79jRrfka8Brt6xchEv5znY?si=jnmhes7-TeadjbnrskoJTQ",
        ),
        (
            5,
            "https://open.spotify.com/album/4gxLcGuGTjg0x5TaKg5wUv?si=N8J8k96RSKaBm3aQ1czEDg",
        ),
        (
            11,
            "https://open.spotify.com/album/5gUcVCRh6D0fWNEJqnw4Su?si=lR25o7qwRMGKWX_0MlApiQ",
        ),
        (
            3,
            "https://open.spotify.com/album/5Ly0j0G8tNqD7ZYkA7Gu1a?si=xJP_uReNS1yupkwJDCaWIA",
        ),
        (
            1,
            "https://open.spotify.com/album/288VEIeQuID3skCNyHeNrH?si=3gULDCyKTjaVGRg3gccfAQ",
        ),
        (
            1,
            "https://open.spotify.com/album/2ZyFLtyUD1jZKESPrmOdI2?si=VCAt288uTD-iO_D_9NpPbQ",
        ),
        (
            1,
            "https://open.spotify.com/album/47ujRWJ1Wp54k0K0si9zwS?si=K-tpolhFQv-7Q5dStqBXtg",
        ),
        (
            6,
            "https://open.spotify.com/album/0wh8YXXxiGVuhnBlhtYuhJ?si=AVCD_q5wQRmlzc3WYpm3ZA",
        ),
        (
            2,
            "https://open.spotify.com/album/7zU1NSsPQbHwXXoEHWa1g8?si=xnhP-MgBSFuzIeCWijcDGQ",
        ),
        (
            8,
            "https://open.spotify.com/album/0riOqrDjuvcMEfI6lbUD39?si=12kBjvE6ThmUimdHfrvvJQ",
        ),
        (
            3,
            "https://open.spotify.com/album/6Phy1JysUYXkDFprinZTFU?si=8O2LN15PRKaY2Pg2K2XskA",
        ),
        (
            4,
            "https://open.spotify.com/album/7ESEpGhOF3pMYF7bIHuWv0?si=obtIcClaQCaZJTDZO1V6Vw",
        ),
        (
            1,
            "https://open.spotify.com/album/6vEJDlvilk1RbxtgajLeyj?si=Q2rjh0MRRSWmjWJYYMlb_Q",
        ),
        (
            3,
            "https://open.spotify.com/album/7lg0uupyKUagvOUJaJfBCv?si=RgzoYkXJRluDIkVxNn5uXw",
        ),
        (
            7,
            "https://open.spotify.com/album/5StNB0XXfonyqYqKRjv8D3?si=hbXPX3dVStGLhuu3tx5J6w",
        ),
        (
            1,
            "https://open.spotify.com/album/0t6x2nFdSUHwCDgMwx7G4x?si=5lWYZdudRE--FS09njTisg",
        ),
        (
            2,
            "https://open.spotify.com/album/2DMuYgkx2SEDgyNiMc61Ht?si=UFQ7TfI1S82hyYxKZiHbBQ",
        ),
        (
            6,
            "https://open.spotify.com/album/3KOtyyImGlWMpPe50K4yfG?si=KAT3ELQLSLGB2Ga4niSDQQ",
        ),
        (
            3,
            "https://open.spotify.com/album/7K9Vi9tL3AWpnoDinnaXgo?si=zQy-uocGT7OqQo7Q5InC8w",
        ),
        (
            1,
            "https://open.spotify.com/album/3jNX8WISj8wszIINYtyDTX?si=SNd84yC4QYaVwLO6g4ATDg",
        ),
        (
            3,
            "https://open.spotify.com/album/7oJFr1NBIY2ZPbDwwAXx9O?si=Wec-v42GRZCdl0MKjD7elg",
        ),
        (
            2,
            "https://open.spotify.com/album/1Jxl7OKYepVoYiX5GDQ5ws?si=NhhlL289RJ2v9ewB1dEDDA",
        ),
        (
            5,
            "https://open.spotify.com/album/3gpbouGEBPdEmAuvZObheF?si=QxzfG-KLT4Ol1axMJUD0PA",
        ),
        (
            8,
            "https://open.spotify.com/album/2L742odVbUTEZ1tOtfL5yH?si=HuLKunmER5qYcR1gD2GDZg",
        ),
        (
            8,
            "https://open.spotify.com/album/4y3eWdqs6F11Gb71QHRX8M?si=SC70iQvrS8a4V1u_wLvpaQ",
        ),
        (
            6,
            "https://open.spotify.com/album/46ZxD77HvAbcpDvHulUJ2C?si=PXhVOkPjQ5iZ3lWnoqG81g",
        ),
        (
            6,
            "https://open.spotify.com/album/28CvSEcvkXPqcv4wiwU5Zn?si=J6042j9jQQO-Au9canmEVQ",
        ),
    ];
    let mut stored_ids: HashSet<String> = HashSet::new();
    for (play_count, url) in entries {
        let parsed_url = Url::parse(url)?;
        let segments = parsed_url
            .path_segments()
            .map(|c| c.collect::<Vec<_>>())
            .ok_or(anyhow::anyhow!("no path available"))?;
        let maybe_entry = match segments[..] {
            ["album", id] => {
                let id = AlbumId::from_id(id)?;
                if stored_ids.contains(&id.uri()) {
                    info!("importing {} already stored", id);
                    continue;
                }
                let album = spotify.album(id, MARKET).await?;
                Ok(EntryCreateModel {
                    name: album.name.clone(),
                    image_url: find_image(album.images.clone())?,
                    entry_type: EntryType::Album,
                    spotify_url: url.to_string(),
                    spotify_uri: album.id.uri(),
                    spotify_id: album.id.id().to_string(),
                    play_count,
                    blob: json!(album),
                    visible: true,
                    category_id: None,
                })
            }
            _ => Err(anyhow::anyhow!("url type not supporeted")),
        };
        let entry = maybe_entry?;
        entries::create(db, entry.clone()).await?;
        stored_ids.insert(entry.spotify_uri);
        thread::sleep(time::Duration::from_millis(200));
    }
    Ok(())
}
fn find_image(images: Vec<Image>) -> anyhow::Result<String> {
    images
        .into_iter()
        .find(with_height)
        .map(|i| i.url.clone())
        .ok_or(anyhow::anyhow!("could not extract image url"))
}
